# Generated by Django 5.0.6 on 2024-07-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='id_str_new',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
