# Generated by Django 5.0.6 on 2024-07-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_article_title_alter_article_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
