services:
  backend:
    restart: always
    image: backend-image
    build:
      context: ./backend
      dockerfile: ./build/Dockerfile
    ports:
      - "5008:5008"
    env_file:
      - ./backend/build/env/dev.env
    volumes:
      - ./backend:/backend
    networks:
      - backend-network
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - ./db/build/env/dev.env
    ports:
      - "5435:5432"
    networks:
      - backend-network

volumes:
  backend:
  db:

networks:
  backend-network:
    driver: bridge
